### ISSUE TITLE
Test and document release process

### ISSUE THREAD

**Issue by ergonlogic** [CiviCRM42/civicrm42-core#3]
I've begun a [wiki page](https://github.com/CiviCRM42/civicrm42-core/wiki/Release-process) to document the 4.2-LTS release process.

In my current tests, the buildmaker.sh script stalls at [line 177](https://github.com/civicrm/civicrm-core/blob/master/distmaker/distmaker.sh#L177), when it tries to generate some XML:

``` bash
cd $DM_SOURCEDIR/xml
$DM_PHP GenCode.php schema/Schema.xml $DM_VERSION
```

This obviously fails, as we appear to have neither an `xml/` directory, the `GenCode.php` script, nor the `xml/schema/Schema.xml` required for this step. Do these need to be backported? Or are they extraneous to 4.2? If the latter, we should probably backport the buildmaker scripts, so we can tweak them to our needs.

**Comment by JoeMurray** [comment]
Yes this is a required step since this builds the DAO layer as well as the sql for the db structure.

I haven't looked at script but one would have expected it to pick up the xml dir from the same repo as the code that goes in the tarball. Like the /tests dir, /xml is not part of the dist itself.

**Comment by mlutfy** [comment]
Yep, seems like patches by Nicolas fixed the issues. I managed to do a test build of 4.2.10 using the instructions in distmaker/README.txt.

Closing this issue. Also updated the [[Release-process]] wiki page.

**Comment by nganivet** [comment]
I have tested the release scripts and they work on my dev server. So I will close this issue and take responsibility for any issues that might surface in the future.

**Comment by nganivet** [comment]
Matthieu DID beat me by a minute or so ... arrrghhh
